{% set name = "git-machete" %}
{% set version = "3.11.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/git-machete-{{ version }}.tar.gz
  sha256: e7e5e4133084f25fe998d532d22f88530d583bbf7474bb0d4a634eff245bdbc2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.6

test:
  imports:
    - git_machete
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VirtusLab/git-machete
  summary: Probably the sharpest git repository organizer & rebase/merge workflow automation tool you've ever seen
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amalota
    - asford
